import { GoogleGenAI, Modality } from "@google/genai";
import type { Product } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const fileToGenerativePart = async (file: File) => {
  const base64EncodedDataPromise = new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (reader.result) {
        resolve((reader.result as string).split(',')[1]);
      } else {
        resolve('');
      }
    };
    reader.readAsDataURL(file);
  });
  return {
    inlineData: { data: await base64EncodedDataPromise, mimeType: file.type },
  };
};

const base64ToGenerativePart = (base64DataUri: string) => {
  const match = base64DataUri.match(/^data:(image\/\w+);base64,(.*)$/);
  if (!match) {
    throw new Error("Invalid data URI string");
  }
  const mimeType = match[1];
  const data = match[2];
  return {
    inlineData: { data, mimeType },
  };
};

export const generateModelImage = async (userPhoto: File, product: Product, productPhoto: string): Promise<string> => {
  try {
    const userImagePart = await fileToGenerativePart(userPhoto);
    const productImagePart = base64ToGenerativePart(productPhoto);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          userImagePart,
          productImagePart,
          { text: product.prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
      }
    }
    
    throw new Error("No image was generated by the API.");
  } catch (error) {
    console.error("Error generating image with Gemini:", error);
    throw error;
  }
};